update debian files

diff --git a/debian/n4d-network.postinst b/debian/n4d-network.postinst
--- a/debian/n4d-network.postinst
+++ b/debian/n4d-network.postinst
@@ -1,8 +1,38 @@
 #!/bin/sh
+# postinst script for n4d-network
+
 set -e
-# N4D module must be enabled to make more easier 
-# the installation process 
-n4d-modules enable-plugin /etc/n4d/conf.d/NetworkManager
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see https://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
+case "$1" in
+    configure)
+	n4d-modules enable-plugin /etc/n4d/conf.d/NetworkManager
+    ;;  
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;  
+
+    *)  
+        echo "postinst called with unknown argument \`$1'" >&2 
+        exit 1
+    ;;  
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
 #DEBHELPER#
 
 exit 0
